// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package inside_payment.tars.rpc.payment;

import com.qq.tars.rpc.protocol.tars.support.TarsAbstractCallback;

public abstract class PaymentControllerPrxCallback extends TarsAbstractCallback {

	public abstract void callback_home(String ret);

	public abstract void callback_pay(ResponsePayment ret);

	public abstract void callback_addMoney(ResponseMoney ret);

	public abstract void callback_query(ResponsePayments ret);

}
