// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package inside_payment.tars.rpc.payment;

import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.annotation.*;
import com.qq.tars.common.support.Holder;

@Servant
public interface PaymentControllerPrx {

	public String home();

	public String home(@TarsContext java.util.Map<String, String> ctx);

	public void async_home(@TarsCallback PaymentControllerPrxCallback callback);

	public void async_home(@TarsCallback PaymentControllerPrxCallback callback, @TarsContext java.util.Map<String, String> ctx);

	public ResponsePayment pay(PaymentTars info);

	public ResponsePayment pay(PaymentTars info, @TarsContext java.util.Map<String, String> ctx);

	public void async_pay(@TarsCallback PaymentControllerPrxCallback callback, PaymentTars info);

	public void async_pay(@TarsCallback PaymentControllerPrxCallback callback, PaymentTars info, @TarsContext java.util.Map<String, String> ctx);

	public ResponseMoney addMoney(PaymentTars info);

	public ResponseMoney addMoney(PaymentTars info, @TarsContext java.util.Map<String, String> ctx);

	public void async_addMoney(@TarsCallback PaymentControllerPrxCallback callback, PaymentTars info);

	public void async_addMoney(@TarsCallback PaymentControllerPrxCallback callback, PaymentTars info, @TarsContext java.util.Map<String, String> ctx);

	public ResponsePayments query();

	public ResponsePayments query(@TarsContext java.util.Map<String, String> ctx);

	public void async_query(@TarsCallback PaymentControllerPrxCallback callback);

	public void async_query(@TarsCallback PaymentControllerPrxCallback callback, @TarsContext java.util.Map<String, String> ctx);
}
