// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package adminbasic.tars.rpc.config;

import com.qq.tars.rpc.protocol.tars.support.TarsAbstractCallback;

public abstract class ConfigControllerPrxCallback extends TarsAbstractCallback {

	public abstract void callback_home(String ret);

	public abstract void callback_queryAll(ResponseConfigs ret);

	public abstract void callback_createConfig(ResponseConfig ret);

	public abstract void callback_updateConfig(ResponseConfig ret);

	public abstract void callback_deleteConfig(ResponseConfig ret);

	public abstract void callback_retrieve(ResponseConfig ret);

}
