// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package adminbasic.tars.rpc.config;

import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.annotation.*;
import com.qq.tars.common.support.Holder;

@Servant
public interface ConfigControllerPrx {

	public String home();

	public String home(@TarsContext java.util.Map<String, String> ctx);

	public void async_home(@TarsCallback ConfigControllerPrxCallback callback);

	public void async_home(@TarsCallback ConfigControllerPrxCallback callback, @TarsContext java.util.Map<String, String> ctx);

	public ResponseConfigs queryAll();

	public ResponseConfigs queryAll(@TarsContext java.util.Map<String, String> ctx);

	public void async_queryAll(@TarsCallback ConfigControllerPrxCallback callback);

	public void async_queryAll(@TarsCallback ConfigControllerPrxCallback callback, @TarsContext java.util.Map<String, String> ctx);

	public ResponseConfig createConfig(ConfigTars info);

	public ResponseConfig createConfig(ConfigTars info, @TarsContext java.util.Map<String, String> ctx);

	public void async_createConfig(@TarsCallback ConfigControllerPrxCallback callback, ConfigTars info);

	public void async_createConfig(@TarsCallback ConfigControllerPrxCallback callback, ConfigTars info, @TarsContext java.util.Map<String, String> ctx);

	public ResponseConfig updateConfig(ConfigTars info);

	public ResponseConfig updateConfig(ConfigTars info, @TarsContext java.util.Map<String, String> ctx);

	public void async_updateConfig(@TarsCallback ConfigControllerPrxCallback callback, ConfigTars info);

	public void async_updateConfig(@TarsCallback ConfigControllerPrxCallback callback, ConfigTars info, @TarsContext java.util.Map<String, String> ctx);

	public ResponseConfig deleteConfig(String configName);

	public ResponseConfig deleteConfig(String configName, @TarsContext java.util.Map<String, String> ctx);

	public void async_deleteConfig(@TarsCallback ConfigControllerPrxCallback callback, String configName);

	public void async_deleteConfig(@TarsCallback ConfigControllerPrxCallback callback, String configName, @TarsContext java.util.Map<String, String> ctx);

	public ResponseConfig retrieve(String configName);

	public ResponseConfig retrieve(String configName, @TarsContext java.util.Map<String, String> ctx);

	public void async_retrieve(@TarsCallback ConfigControllerPrxCallback callback, String configName);

	public void async_retrieve(@TarsCallback ConfigControllerPrxCallback callback, String configName, @TarsContext java.util.Map<String, String> ctx);
}
