// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package com.trainticket.tars.payment;

import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.annotation.*;
import com.qq.tars.common.support.Holder;

@Servant
public interface PaymentControllerServant {

	public String home();

	public ResponsePayment pay(PaymentTars info);

	public ResponseMoney addMoney(PaymentTars info);

	public ResponsePayments query();
}
