// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package inside_payment.tars.rpc.orderother;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class SoldTicketTars {

	@TarsStructProperty(order = 0, isRequire = false)
	public long travelDate = 0;
	@TarsStructProperty(order = 1, isRequire = false)
	public String trainNumber = "";
	@TarsStructProperty(order = 2, isRequire = false)
	public int noSeat = 0;
	@TarsStructProperty(order = 3, isRequire = false)
	public int businessSeat = 0;
	@TarsStructProperty(order = 4, isRequire = false)
	public int firstClassSeat = 0;
	@TarsStructProperty(order = 5, isRequire = false)
	public int secondClassSeat = 0;
	@TarsStructProperty(order = 6, isRequire = false)
	public int hardSeat = 0;
	@TarsStructProperty(order = 7, isRequire = false)
	public int softSeat = 0;
	@TarsStructProperty(order = 8, isRequire = false)
	public int hardBed = 0;
	@TarsStructProperty(order = 9, isRequire = false)
	public int softBed = 0;
	@TarsStructProperty(order = 10, isRequire = false)
	public int highSoftBed = 0;

	public long getTravelDate() {
		return travelDate;
	}

	public void setTravelDate(long travelDate) {
		this.travelDate = travelDate;
	}

	public String getTrainNumber() {
		return trainNumber;
	}

	public void setTrainNumber(String trainNumber) {
		this.trainNumber = trainNumber;
	}

	public int getNoSeat() {
		return noSeat;
	}

	public void setNoSeat(int noSeat) {
		this.noSeat = noSeat;
	}

	public int getBusinessSeat() {
		return businessSeat;
	}

	public void setBusinessSeat(int businessSeat) {
		this.businessSeat = businessSeat;
	}

	public int getFirstClassSeat() {
		return firstClassSeat;
	}

	public void setFirstClassSeat(int firstClassSeat) {
		this.firstClassSeat = firstClassSeat;
	}

	public int getSecondClassSeat() {
		return secondClassSeat;
	}

	public void setSecondClassSeat(int secondClassSeat) {
		this.secondClassSeat = secondClassSeat;
	}

	public int getHardSeat() {
		return hardSeat;
	}

	public void setHardSeat(int hardSeat) {
		this.hardSeat = hardSeat;
	}

	public int getSoftSeat() {
		return softSeat;
	}

	public void setSoftSeat(int softSeat) {
		this.softSeat = softSeat;
	}

	public int getHardBed() {
		return hardBed;
	}

	public void setHardBed(int hardBed) {
		this.hardBed = hardBed;
	}

	public int getSoftBed() {
		return softBed;
	}

	public void setSoftBed(int softBed) {
		this.softBed = softBed;
	}

	public int getHighSoftBed() {
		return highSoftBed;
	}

	public void setHighSoftBed(int highSoftBed) {
		this.highSoftBed = highSoftBed;
	}

	public SoldTicketTars() {
	}

	public SoldTicketTars(long travelDate, String trainNumber, int noSeat, int businessSeat, int firstClassSeat, int secondClassSeat, int hardSeat, int softSeat, int hardBed, int softBed, int highSoftBed) {
		this.travelDate = travelDate;
		this.trainNumber = trainNumber;
		this.noSeat = noSeat;
		this.businessSeat = businessSeat;
		this.firstClassSeat = firstClassSeat;
		this.secondClassSeat = secondClassSeat;
		this.hardSeat = hardSeat;
		this.softSeat = softSeat;
		this.hardBed = hardBed;
		this.softBed = softBed;
		this.highSoftBed = highSoftBed;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(travelDate);
		result = prime * result + TarsUtil.hashCode(trainNumber);
		result = prime * result + TarsUtil.hashCode(noSeat);
		result = prime * result + TarsUtil.hashCode(businessSeat);
		result = prime * result + TarsUtil.hashCode(firstClassSeat);
		result = prime * result + TarsUtil.hashCode(secondClassSeat);
		result = prime * result + TarsUtil.hashCode(hardSeat);
		result = prime * result + TarsUtil.hashCode(softSeat);
		result = prime * result + TarsUtil.hashCode(hardBed);
		result = prime * result + TarsUtil.hashCode(softBed);
		result = prime * result + TarsUtil.hashCode(highSoftBed);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof SoldTicketTars)) {
			return false;
		}
		SoldTicketTars other = (SoldTicketTars) obj;
		return (
			TarsUtil.equals(travelDate, other.travelDate) &&
			TarsUtil.equals(trainNumber, other.trainNumber) &&
			TarsUtil.equals(noSeat, other.noSeat) &&
			TarsUtil.equals(businessSeat, other.businessSeat) &&
			TarsUtil.equals(firstClassSeat, other.firstClassSeat) &&
			TarsUtil.equals(secondClassSeat, other.secondClassSeat) &&
			TarsUtil.equals(hardSeat, other.hardSeat) &&
			TarsUtil.equals(softSeat, other.softSeat) &&
			TarsUtil.equals(hardBed, other.hardBed) &&
			TarsUtil.equals(softBed, other.softBed) &&
			TarsUtil.equals(highSoftBed, other.highSoftBed) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(travelDate, 0);
		if (null != trainNumber) {
			_os.write(trainNumber, 1);
		}
		_os.write(noSeat, 2);
		_os.write(businessSeat, 3);
		_os.write(firstClassSeat, 4);
		_os.write(secondClassSeat, 5);
		_os.write(hardSeat, 6);
		_os.write(softSeat, 7);
		_os.write(hardBed, 8);
		_os.write(softBed, 9);
		_os.write(highSoftBed, 10);
	}


	public void readFrom(TarsInputStream _is) {
		this.travelDate = _is.read(travelDate, 0, false);
		this.trainNumber = _is.readString(1, false);
		this.noSeat = _is.read(noSeat, 2, false);
		this.businessSeat = _is.read(businessSeat, 3, false);
		this.firstClassSeat = _is.read(firstClassSeat, 4, false);
		this.secondClassSeat = _is.read(secondClassSeat, 5, false);
		this.hardSeat = _is.read(hardSeat, 6, false);
		this.softSeat = _is.read(softSeat, 7, false);
		this.hardBed = _is.read(hardBed, 8, false);
		this.softBed = _is.read(softBed, 9, false);
		this.highSoftBed = _is.read(highSoftBed, 10, false);
	}

}
