// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package execute.tars.rpc.orderother;

import com.qq.tars.rpc.protocol.tars.support.TarsAbstractCallback;

public abstract class OrderOtherControllerPrxCallback extends TarsAbstractCallback {

	public abstract void callback_home(String ret);

	public abstract void callback_getTicketListByDateAndTripId(ResponseLeftTicketInfo ret);

	public abstract void callback_createNewOrder(ResponseOrder ret);

	public abstract void callback_addcreateNewOrder(ResponseOrder ret);

	public abstract void callback_queryOrders(ResponseOrderList ret);

	public abstract void callback_queryOrdersForRefresh(ResponseOrderList ret);

	public abstract void callback_calculateSoldTicket(ResponseSoldTicket ret);

	public abstract void callback_getOrderPrice(ResponseString ret);

	public abstract void callback_payOrder(ResponseOrder ret);

	public abstract void callback_getOrderById(ResponseOrder ret);

	public abstract void callback_modifyOrder(ResponseOrder ret);

	public abstract void callback_securityInfoCheck(ResponseOrderSecurity ret);

	public abstract void callback_saveOrderInfo(ResponseOrder ret);

	public abstract void callback_updateOrder(ResponseOrder ret);

	public abstract void callback_deleteOrder(ResponseString ret);

	public abstract void callback_findAllOrder(ResponseOrderList ret);

}
