// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package consign.tars.rpc.consignprice;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class ConsignPriceTars {

	@TarsStructProperty(order = 0, isRequire = false)
	public String id = "";
	@TarsStructProperty(order = 1, isRequire = false)
	public int index = 0;
	@TarsStructProperty(order = 2, isRequire = false)
	public double initialWeight = 0;
	@TarsStructProperty(order = 3, isRequire = false)
	public double initialPrice = 0;
	@TarsStructProperty(order = 4, isRequire = false)
	public double withinPrice = 0;
	@TarsStructProperty(order = 5, isRequire = false)
	public double beyondPrice = 0;

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public int getIndex() {
		return index;
	}

	public void setIndex(int index) {
		this.index = index;
	}

	public double getInitialWeight() {
		return initialWeight;
	}

	public void setInitialWeight(double initialWeight) {
		this.initialWeight = initialWeight;
	}

	public double getInitialPrice() {
		return initialPrice;
	}

	public void setInitialPrice(double initialPrice) {
		this.initialPrice = initialPrice;
	}

	public double getWithinPrice() {
		return withinPrice;
	}

	public void setWithinPrice(double withinPrice) {
		this.withinPrice = withinPrice;
	}

	public double getBeyondPrice() {
		return beyondPrice;
	}

	public void setBeyondPrice(double beyondPrice) {
		this.beyondPrice = beyondPrice;
	}

	public ConsignPriceTars() {
	}

	public ConsignPriceTars(String id, int index, double initialWeight, double initialPrice, double withinPrice, double beyondPrice) {
		this.id = id;
		this.index = index;
		this.initialWeight = initialWeight;
		this.initialPrice = initialPrice;
		this.withinPrice = withinPrice;
		this.beyondPrice = beyondPrice;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(id);
		result = prime * result + TarsUtil.hashCode(index);
		result = prime * result + TarsUtil.hashCode(initialWeight);
		result = prime * result + TarsUtil.hashCode(initialPrice);
		result = prime * result + TarsUtil.hashCode(withinPrice);
		result = prime * result + TarsUtil.hashCode(beyondPrice);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof ConsignPriceTars)) {
			return false;
		}
		ConsignPriceTars other = (ConsignPriceTars) obj;
		return (
			TarsUtil.equals(id, other.id) &&
			TarsUtil.equals(index, other.index) &&
			TarsUtil.equals(initialWeight, other.initialWeight) &&
			TarsUtil.equals(initialPrice, other.initialPrice) &&
			TarsUtil.equals(withinPrice, other.withinPrice) &&
			TarsUtil.equals(beyondPrice, other.beyondPrice) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != id) {
			_os.write(id, 0);
		}
		_os.write(index, 1);
		_os.write(initialWeight, 2);
		_os.write(initialPrice, 3);
		_os.write(withinPrice, 4);
		_os.write(beyondPrice, 5);
	}


	public void readFrom(TarsInputStream _is) {
		this.id = _is.readString(0, false);
		this.index = _is.read(index, 1, false);
		this.initialWeight = _is.read(initialWeight, 2, false);
		this.initialPrice = _is.read(initialPrice, 3, false);
		this.withinPrice = _is.read(withinPrice, 4, false);
		this.beyondPrice = _is.read(beyondPrice, 5, false);
	}

}
