// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package consign.tars.rpc.consignprice;

import com.qq.tars.rpc.protocol.tars.support.TarsAbstractCallback;

public abstract class ConsignPriceControllerPrxCallback extends TarsAbstractCallback {

	public abstract void callback_home(String ret);

	public abstract void callback_getPriceByWeightAndRegion(ResponseDouble ret);

	public abstract void callback_getPriceInfo(ResponseString ret);

	public abstract void callback_getPriceConfig(ResponseConsignPrice ret);

	public abstract void callback_modifyPriceConfig(ResponseConsignPrice ret);

}
