// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package consign.tars.rpc.consignprice;

import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.annotation.*;
import com.qq.tars.common.support.Holder;

@Servant
public interface ConsignPriceControllerPrx {

	public String home();

	public String home(@TarsContext java.util.Map<String, String> ctx);

	public void async_home(@TarsCallback ConsignPriceControllerPrxCallback callback);

	public void async_home(@TarsCallback ConsignPriceControllerPrxCallback callback, @TarsContext java.util.Map<String, String> ctx);

	public ResponseDouble getPriceByWeightAndRegion(String weight, String isWithinRegion);

	public ResponseDouble getPriceByWeightAndRegion(String weight, String isWithinRegion, @TarsContext java.util.Map<String, String> ctx);

	public void async_getPriceByWeightAndRegion(@TarsCallback ConsignPriceControllerPrxCallback callback, String weight, String isWithinRegion);

	public void async_getPriceByWeightAndRegion(@TarsCallback ConsignPriceControllerPrxCallback callback, String weight, String isWithinRegion, @TarsContext java.util.Map<String, String> ctx);

	public ResponseString getPriceInfo();

	public ResponseString getPriceInfo(@TarsContext java.util.Map<String, String> ctx);

	public void async_getPriceInfo(@TarsCallback ConsignPriceControllerPrxCallback callback);

	public void async_getPriceInfo(@TarsCallback ConsignPriceControllerPrxCallback callback, @TarsContext java.util.Map<String, String> ctx);

	public ResponseConsignPrice getPriceConfig();

	public ResponseConsignPrice getPriceConfig(@TarsContext java.util.Map<String, String> ctx);

	public void async_getPriceConfig(@TarsCallback ConsignPriceControllerPrxCallback callback);

	public void async_getPriceConfig(@TarsCallback ConsignPriceControllerPrxCallback callback, @TarsContext java.util.Map<String, String> ctx);

	public ResponseConsignPrice modifyPriceConfig(ConsignPriceTars priceConfig);

	public ResponseConsignPrice modifyPriceConfig(ConsignPriceTars priceConfig, @TarsContext java.util.Map<String, String> ctx);

	public void async_modifyPriceConfig(@TarsCallback ConsignPriceControllerPrxCallback callback, ConsignPriceTars priceConfig);

	public void async_modifyPriceConfig(@TarsCallback ConsignPriceControllerPrxCallback callback, ConsignPriceTars priceConfig, @TarsContext java.util.Map<String, String> ctx);
}
