// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package config.tars.config;

import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.annotation.*;
import com.qq.tars.common.support.Holder;

@Servant
public interface ConfigControllerServant {

	public String home();

	public ResponseConfigs queryAll();

	public ResponseConfig createConfig(ConfigTars info);

	public ResponseConfig updateConfig(ConfigTars info);

	public ResponseConfig deleteConfig(String configName);

	public ResponseConfig retrieve(String configName);
}
