// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package fdse.microservice.tars.rpc.priceconfig;

import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.annotation.*;
import com.qq.tars.common.support.Holder;

@Servant
public interface PriceControllerPrx {

	public String home();

	public String home(@TarsContext java.util.Map<String, String> ctx);

	public void async_home(@TarsCallback PriceControllerPrxCallback callback);

	public void async_home(@TarsCallback PriceControllerPrxCallback callback, @TarsContext java.util.Map<String, String> ctx);

	public ResponsePriceConfig query(String routeId, String trainType);

	public ResponsePriceConfig query(String routeId, String trainType, @TarsContext java.util.Map<String, String> ctx);

	public void async_query(@TarsCallback PriceControllerPrxCallback callback, String routeId, String trainType);

	public void async_query(@TarsCallback PriceControllerPrxCallback callback, String routeId, String trainType, @TarsContext java.util.Map<String, String> ctx);

	public ResponsePriceConfigs queryAll();

	public ResponsePriceConfigs queryAll(@TarsContext java.util.Map<String, String> ctx);

	public void async_queryAll(@TarsCallback PriceControllerPrxCallback callback);

	public void async_queryAll(@TarsCallback PriceControllerPrxCallback callback, @TarsContext java.util.Map<String, String> ctx);

	public ResponsePriceConfig create(PriceConfigTars info);

	public ResponsePriceConfig create(PriceConfigTars info, @TarsContext java.util.Map<String, String> ctx);

	public void async_create(@TarsCallback PriceControllerPrxCallback callback, PriceConfigTars info);

	public void async_create(@TarsCallback PriceControllerPrxCallback callback, PriceConfigTars info, @TarsContext java.util.Map<String, String> ctx);

	public ResponsePriceConfig delete(PriceConfigTars info);

	public ResponsePriceConfig delete(PriceConfigTars info, @TarsContext java.util.Map<String, String> ctx);

	public void async_delete(@TarsCallback PriceControllerPrxCallback callback, PriceConfigTars info);

	public void async_delete(@TarsCallback PriceControllerPrxCallback callback, PriceConfigTars info, @TarsContext java.util.Map<String, String> ctx);

	public ResponsePriceConfig update(PriceConfigTars info);

	public ResponsePriceConfig update(PriceConfigTars info, @TarsContext java.util.Map<String, String> ctx);

	public void async_update(@TarsCallback PriceControllerPrxCallback callback, PriceConfigTars info);

	public void async_update(@TarsCallback PriceControllerPrxCallback callback, PriceConfigTars info, @TarsContext java.util.Map<String, String> ctx);
}
