// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package adminorder.tars.rpc.orderother;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class SeatTars {

	@TarsStructProperty(order = 0, isRequire = false)
	public long travelDate = 0;
	@TarsStructProperty(order = 1, isRequire = false)
	public String trainNumber = "";
	@TarsStructProperty(order = 2, isRequire = false)
	public String startStation = "";
	@TarsStructProperty(order = 3, isRequire = false)
	public String destStation = "";
	@TarsStructProperty(order = 4, isRequire = false)
	public int seatType = 0;

	public long getTravelDate() {
		return travelDate;
	}

	public void setTravelDate(long travelDate) {
		this.travelDate = travelDate;
	}

	public String getTrainNumber() {
		return trainNumber;
	}

	public void setTrainNumber(String trainNumber) {
		this.trainNumber = trainNumber;
	}

	public String getStartStation() {
		return startStation;
	}

	public void setStartStation(String startStation) {
		this.startStation = startStation;
	}

	public String getDestStation() {
		return destStation;
	}

	public void setDestStation(String destStation) {
		this.destStation = destStation;
	}

	public int getSeatType() {
		return seatType;
	}

	public void setSeatType(int seatType) {
		this.seatType = seatType;
	}

	public SeatTars() {
	}

	public SeatTars(long travelDate, String trainNumber, String startStation, String destStation, int seatType) {
		this.travelDate = travelDate;
		this.trainNumber = trainNumber;
		this.startStation = startStation;
		this.destStation = destStation;
		this.seatType = seatType;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(travelDate);
		result = prime * result + TarsUtil.hashCode(trainNumber);
		result = prime * result + TarsUtil.hashCode(startStation);
		result = prime * result + TarsUtil.hashCode(destStation);
		result = prime * result + TarsUtil.hashCode(seatType);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof SeatTars)) {
			return false;
		}
		SeatTars other = (SeatTars) obj;
		return (
			TarsUtil.equals(travelDate, other.travelDate) &&
			TarsUtil.equals(trainNumber, other.trainNumber) &&
			TarsUtil.equals(startStation, other.startStation) &&
			TarsUtil.equals(destStation, other.destStation) &&
			TarsUtil.equals(seatType, other.seatType) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(travelDate, 0);
		if (null != trainNumber) {
			_os.write(trainNumber, 1);
		}
		if (null != startStation) {
			_os.write(startStation, 2);
		}
		if (null != destStation) {
			_os.write(destStation, 3);
		}
		_os.write(seatType, 4);
	}


	public void readFrom(TarsInputStream _is) {
		this.travelDate = _is.read(travelDate, 0, false);
		this.trainNumber = _is.readString(1, false);
		this.startStation = _is.readString(2, false);
		this.destStation = _is.readString(3, false);
		this.seatType = _is.read(seatType, 4, false);
	}

}
