// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package security.tars.security;

import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.annotation.*;
import com.qq.tars.common.support.Holder;

@Servant
public interface SecurityControllerServant {

	public String home();

	public Response findAllSecurityConfig(@TarsHolder Holder<java.util.List<SecurityConfigTars>> outData);

	public Response create(SecurityConfigTars info, @TarsHolder Holder<SecurityConfigTars> outData);

	public Response update(SecurityConfigTars info, @TarsHolder Holder<SecurityConfigTars> outData);

	public Response delete(String id, @TarsHolder Holder<String> outData);

	public Response check(String accountId, @TarsHolder Holder<String> outData);
}
