// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package adminroute.tars.adminroute;

import adminroute.tars.rpc.route.ResponseRoute;
import adminroute.tars.rpc.route.ResponseRoutes;
import adminroute.tars.rpc.route.ResponseString;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.annotation.*;
import com.qq.tars.common.support.Holder;

@Servant
public interface AdminRouteControllerServant {

	public String home();

	public ResponseRoutes getAllRoutes();

	public ResponseRoute addRoute(RouteInfoTars request);

	public ResponseString deleteRoute(String routeId);
}
