// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package order.tars.rpc.station;

import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.annotation.*;
import com.qq.tars.common.support.Holder;

@Servant
public interface StationControllerPrx {

	public String home();

	public String home(@TarsContext java.util.Map<String, String> ctx);

	public void async_home(@TarsCallback StationControllerPrxCallback callback);

	public void async_home(@TarsCallback StationControllerPrxCallback callback, @TarsContext java.util.Map<String, String> ctx);

	public ResponseStations query();

	public ResponseStations query(@TarsContext java.util.Map<String, String> ctx);

	public void async_query(@TarsCallback StationControllerPrxCallback callback);

	public void async_query(@TarsCallback StationControllerPrxCallback callback, @TarsContext java.util.Map<String, String> ctx);

	public ResponseStation create(StationTars station);

	public ResponseStation create(StationTars station, @TarsContext java.util.Map<String, String> ctx);

	public void async_create(@TarsCallback StationControllerPrxCallback callback, StationTars station);

	public void async_create(@TarsCallback StationControllerPrxCallback callback, StationTars station, @TarsContext java.util.Map<String, String> ctx);

	public ResponseStation update(StationTars station);

	public ResponseStation update(StationTars station, @TarsContext java.util.Map<String, String> ctx);

	public void async_update(@TarsCallback StationControllerPrxCallback callback, StationTars station);

	public void async_update(@TarsCallback StationControllerPrxCallback callback, StationTars station, @TarsContext java.util.Map<String, String> ctx);

	public ResponseStation delete(StationTars station);

	public ResponseStation delete(StationTars station, @TarsContext java.util.Map<String, String> ctx);

	public void async_delete(@TarsCallback StationControllerPrxCallback callback, StationTars station);

	public void async_delete(@TarsCallback StationControllerPrxCallback callback, StationTars station, @TarsContext java.util.Map<String, String> ctx);

	public ResponseString queryForStationId(String stationName);

	public ResponseString queryForStationId(String stationName, @TarsContext java.util.Map<String, String> ctx);

	public void async_queryForStationId(@TarsCallback StationControllerPrxCallback callback, String stationName);

	public void async_queryForStationId(@TarsCallback StationControllerPrxCallback callback, String stationName, @TarsContext java.util.Map<String, String> ctx);

	public ResponseStringList queryForIdBatch(java.util.List<String> stationNameList);

	public ResponseStringList queryForIdBatch(java.util.List<String> stationNameList, @TarsContext java.util.Map<String, String> ctx);

	public void async_queryForIdBatch(@TarsCallback StationControllerPrxCallback callback, java.util.List<String> stationNameList);

	public void async_queryForIdBatch(@TarsCallback StationControllerPrxCallback callback, java.util.List<String> stationNameList, @TarsContext java.util.Map<String, String> ctx);

	public ResponseString queryById(String stationId);

	public ResponseString queryById(String stationId, @TarsContext java.util.Map<String, String> ctx);

	public void async_queryById(@TarsCallback StationControllerPrxCallback callback, String stationId);

	public void async_queryById(@TarsCallback StationControllerPrxCallback callback, String stationId, @TarsContext java.util.Map<String, String> ctx);

	public ResponseStringList queryForNameBatch(java.util.List<String> stationIdList);

	public ResponseStringList queryForNameBatch(java.util.List<String> stationIdList, @TarsContext java.util.Map<String, String> ctx);

	public void async_queryForNameBatch(@TarsCallback StationControllerPrxCallback callback, java.util.List<String> stationIdList);

	public void async_queryForNameBatch(@TarsCallback StationControllerPrxCallback callback, java.util.List<String> stationIdList, @TarsContext java.util.Map<String, String> ctx);
}
