// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package fdse.microservice.tars.rpc.train;

import com.qq.tars.rpc.protocol.tars.support.TarsAbstractCallback;

public abstract class TrainControllerPrxCallback extends TarsAbstractCallback {

	public abstract void callback_home(String ret);

	public abstract void callback_create(ResponseTrainType ret);

	public abstract void callback_retrieve(ResponseTrainType ret);

	public abstract void callback_update(ResponseTrainType ret);

	public abstract void callback_delete(ResponseTrainType ret);

	public abstract void callback_query(ResponseTrainTypes ret);

}
