// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package security.tars.rpc.order;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class OrderInfoTars {

	@TarsStructProperty(order = 0, isRequire = false)
	public String loginId = "";
	@TarsStructProperty(order = 1, isRequire = false)
	public long travelDateStart = 0;
	@TarsStructProperty(order = 2, isRequire = false)
	public long travelDateEnd = 0;
	@TarsStructProperty(order = 3, isRequire = false)
	public long boughtDateStart = 0;
	@TarsStructProperty(order = 4, isRequire = false)
	public long boughtDateEnd = 0;
	@TarsStructProperty(order = 5, isRequire = false)
	public int state = 0;
	@TarsStructProperty(order = 6, isRequire = false)
	public boolean enableTravelDateQuery = false;
	@TarsStructProperty(order = 7, isRequire = false)
	public boolean enableBoughtDateQuery = false;
	@TarsStructProperty(order = 8, isRequire = false)
	public boolean enableStateQuery = false;

	public String getLoginId() {
		return loginId;
	}

	public void setLoginId(String loginId) {
		this.loginId = loginId;
	}

	public long getTravelDateStart() {
		return travelDateStart;
	}

	public void setTravelDateStart(long travelDateStart) {
		this.travelDateStart = travelDateStart;
	}

	public long getTravelDateEnd() {
		return travelDateEnd;
	}

	public void setTravelDateEnd(long travelDateEnd) {
		this.travelDateEnd = travelDateEnd;
	}

	public long getBoughtDateStart() {
		return boughtDateStart;
	}

	public void setBoughtDateStart(long boughtDateStart) {
		this.boughtDateStart = boughtDateStart;
	}

	public long getBoughtDateEnd() {
		return boughtDateEnd;
	}

	public void setBoughtDateEnd(long boughtDateEnd) {
		this.boughtDateEnd = boughtDateEnd;
	}

	public int getState() {
		return state;
	}

	public void setState(int state) {
		this.state = state;
	}

	public boolean getEnableTravelDateQuery() {
		return enableTravelDateQuery;
	}

	public void setEnableTravelDateQuery(boolean enableTravelDateQuery) {
		this.enableTravelDateQuery = enableTravelDateQuery;
	}

	public boolean getEnableBoughtDateQuery() {
		return enableBoughtDateQuery;
	}

	public void setEnableBoughtDateQuery(boolean enableBoughtDateQuery) {
		this.enableBoughtDateQuery = enableBoughtDateQuery;
	}

	public boolean getEnableStateQuery() {
		return enableStateQuery;
	}

	public void setEnableStateQuery(boolean enableStateQuery) {
		this.enableStateQuery = enableStateQuery;
	}

	public OrderInfoTars() {
	}

	public OrderInfoTars(String loginId, long travelDateStart, long travelDateEnd, long boughtDateStart, long boughtDateEnd, int state, boolean enableTravelDateQuery, boolean enableBoughtDateQuery, boolean enableStateQuery) {
		this.loginId = loginId;
		this.travelDateStart = travelDateStart;
		this.travelDateEnd = travelDateEnd;
		this.boughtDateStart = boughtDateStart;
		this.boughtDateEnd = boughtDateEnd;
		this.state = state;
		this.enableTravelDateQuery = enableTravelDateQuery;
		this.enableBoughtDateQuery = enableBoughtDateQuery;
		this.enableStateQuery = enableStateQuery;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(loginId);
		result = prime * result + TarsUtil.hashCode(travelDateStart);
		result = prime * result + TarsUtil.hashCode(travelDateEnd);
		result = prime * result + TarsUtil.hashCode(boughtDateStart);
		result = prime * result + TarsUtil.hashCode(boughtDateEnd);
		result = prime * result + TarsUtil.hashCode(state);
		result = prime * result + TarsUtil.hashCode(enableTravelDateQuery);
		result = prime * result + TarsUtil.hashCode(enableBoughtDateQuery);
		result = prime * result + TarsUtil.hashCode(enableStateQuery);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof OrderInfoTars)) {
			return false;
		}
		OrderInfoTars other = (OrderInfoTars) obj;
		return (
			TarsUtil.equals(loginId, other.loginId) &&
			TarsUtil.equals(travelDateStart, other.travelDateStart) &&
			TarsUtil.equals(travelDateEnd, other.travelDateEnd) &&
			TarsUtil.equals(boughtDateStart, other.boughtDateStart) &&
			TarsUtil.equals(boughtDateEnd, other.boughtDateEnd) &&
			TarsUtil.equals(state, other.state) &&
			TarsUtil.equals(enableTravelDateQuery, other.enableTravelDateQuery) &&
			TarsUtil.equals(enableBoughtDateQuery, other.enableBoughtDateQuery) &&
			TarsUtil.equals(enableStateQuery, other.enableStateQuery) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != loginId) {
			_os.write(loginId, 0);
		}
		_os.write(travelDateStart, 1);
		_os.write(travelDateEnd, 2);
		_os.write(boughtDateStart, 3);
		_os.write(boughtDateEnd, 4);
		_os.write(state, 5);
		_os.write(enableTravelDateQuery, 6);
		_os.write(enableBoughtDateQuery, 7);
		_os.write(enableStateQuery, 8);
	}


	public void readFrom(TarsInputStream _is) {
		this.loginId = _is.readString(0, false);
		this.travelDateStart = _is.read(travelDateStart, 1, false);
		this.travelDateEnd = _is.read(travelDateEnd, 2, false);
		this.boughtDateStart = _is.read(boughtDateStart, 3, false);
		this.boughtDateEnd = _is.read(boughtDateEnd, 4, false);
		this.state = _is.read(state, 5, false);
		this.enableTravelDateQuery = _is.read(enableTravelDateQuery, 6, false);
		this.enableBoughtDateQuery = _is.read(enableBoughtDateQuery, 7, false);
		this.enableStateQuery = _is.read(enableStateQuery, 8, false);
	}

}
