// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package ticketinfo.tars.ticketinfo;

import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.annotation.*;
import com.qq.tars.common.support.Holder;
import ticketinfo.tars.rpc.basic.TravelResultTars;
import ticketinfo.tars.rpc.basic.TravelTars;

@Servant
public interface TicketInfoControllerServant {

	public String home();

	public Response queryForTravel(TravelTars info, @TarsHolder Holder<TravelResultTars> outData);

	public Response queryForStationId(String name, @TarsHolder Holder<String> outData);
}
