// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package adminbasic.tars.rpc.contacts;

import com.qq.tars.rpc.protocol.tars.support.TarsAbstractCallback;

public abstract class ContactsControllerPrxCallback extends TarsAbstractCallback {

	public abstract void callback_home(String ret);

	public abstract void callback_getAllContacts(ResponseContactsList ret);

	public abstract void callback_createNewContacts(ResponseContacts ret);

	public abstract void callback_createNewContactsAdmin(ResponseContacts ret);

	public abstract void callback_deleteContacts(ResponseString ret);

	public abstract void callback_modifyContacts(ResponseContacts ret);

	public abstract void callback_findContactsByAccountId(ResponseContactsList ret);

	public abstract void callback_getContactsByContactsId(ResponseContacts ret);

}
