// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package adminroute.tars.rpc.route;

import com.qq.tars.rpc.protocol.tars.support.TarsAbstractCallback;

public abstract class RouteControllerPrxCallback extends TarsAbstractCallback {

	public abstract void callback_home(String ret);

	public abstract void callback_createAndModifyRoute(ResponseRoute ret);

	public abstract void callback_deleteRoute(ResponseString ret);

	public abstract void callback_queryById(ResponseRoute ret);

	public abstract void callback_queryAll(ResponseRoutes ret);

	public abstract void callback_queryByStartAndTerminal(ResponseRoutes ret);

}
