// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package adminroute.tars.rpc.route;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class RouteInfoTars {

	@TarsStructProperty(order = 0, isRequire = false)
	public String id = "";
	@TarsStructProperty(order = 1, isRequire = false)
	public String startStation = "";
	@TarsStructProperty(order = 2, isRequire = false)
	public String endStation = "";
	@TarsStructProperty(order = 3, isRequire = false)
	public String stationList = "";
	@TarsStructProperty(order = 4, isRequire = false)
	public String distanceList = "";

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getStartStation() {
		return startStation;
	}

	public void setStartStation(String startStation) {
		this.startStation = startStation;
	}

	public String getEndStation() {
		return endStation;
	}

	public void setEndStation(String endStation) {
		this.endStation = endStation;
	}

	public String getStationList() {
		return stationList;
	}

	public void setStationList(String stationList) {
		this.stationList = stationList;
	}

	public String getDistanceList() {
		return distanceList;
	}

	public void setDistanceList(String distanceList) {
		this.distanceList = distanceList;
	}

	public RouteInfoTars() {
	}

	public RouteInfoTars(String id, String startStation, String endStation, String stationList, String distanceList) {
		this.id = id;
		this.startStation = startStation;
		this.endStation = endStation;
		this.stationList = stationList;
		this.distanceList = distanceList;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(id);
		result = prime * result + TarsUtil.hashCode(startStation);
		result = prime * result + TarsUtil.hashCode(endStation);
		result = prime * result + TarsUtil.hashCode(stationList);
		result = prime * result + TarsUtil.hashCode(distanceList);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof RouteInfoTars)) {
			return false;
		}
		RouteInfoTars other = (RouteInfoTars) obj;
		return (
			TarsUtil.equals(id, other.id) &&
			TarsUtil.equals(startStation, other.startStation) &&
			TarsUtil.equals(endStation, other.endStation) &&
			TarsUtil.equals(stationList, other.stationList) &&
			TarsUtil.equals(distanceList, other.distanceList) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != id) {
			_os.write(id, 0);
		}
		if (null != startStation) {
			_os.write(startStation, 1);
		}
		if (null != endStation) {
			_os.write(endStation, 2);
		}
		if (null != stationList) {
			_os.write(stationList, 3);
		}
		if (null != distanceList) {
			_os.write(distanceList, 4);
		}
	}


	public void readFrom(TarsInputStream _is) {
		this.id = _is.readString(0, false);
		this.startStation = _is.readString(1, false);
		this.endStation = _is.readString(2, false);
		this.stationList = _is.readString(3, false);
		this.distanceList = _is.readString(4, false);
	}

}
