// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package ticketinfo.tars.rpc.basic;

import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.annotation.*;
import com.qq.tars.common.support.Holder;

@Servant
public interface BasicControllerPrx {

	public String home();

	public String home(@TarsContext java.util.Map<String, String> ctx);

	public void async_home(@TarsCallback BasicControllerPrxCallback callback);

	public void async_home(@TarsCallback BasicControllerPrxCallback callback, @TarsContext java.util.Map<String, String> ctx);

	public ResponseTravelResult queryForTravel(TravelTars info);

	public ResponseTravelResult queryForTravel(TravelTars info, @TarsContext java.util.Map<String, String> ctx);

	public void async_queryForTravel(@TarsCallback BasicControllerPrxCallback callback, TravelTars info);

	public void async_queryForTravel(@TarsCallback BasicControllerPrxCallback callback, TravelTars info, @TarsContext java.util.Map<String, String> ctx);

	public ResponseString queryForStationId(String stationName);

	public ResponseString queryForStationId(String stationName, @TarsContext java.util.Map<String, String> ctx);

	public void async_queryForStationId(@TarsCallback BasicControllerPrxCallback callback, String stationName);

	public void async_queryForStationId(@TarsCallback BasicControllerPrxCallback callback, String stationName, @TarsContext java.util.Map<String, String> ctx);
}
