// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package contacts.tars.contacts;

import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.annotation.*;
import com.qq.tars.common.support.Holder;

@Servant
public interface ContactsControllerServant {

	public String home();

	public ResponseContactsList getAllContacts();

	public ResponseContacts createNewContacts(ContactsTars aci);

	public ResponseContacts createNewContactsAdmin(ContactsTars aci);

	public ResponseString deleteContacts(String contactsId);

	public ResponseContacts modifyContacts(ContactsTars info);

	public ResponseContactsList findContactsByAccountId(String accountId);

	public ResponseContacts getContactsByContactsId(String id);
}
