// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package assurance.tars.assurance;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class AssuranceTars {

	@TarsStructProperty(order = 0, isRequire = false)
	public String id = "";
	@TarsStructProperty(order = 1, isRequire = false)
	public String orderId = "";
	@TarsStructProperty(order = 2, isRequire = false)
	public AssuranceTypeTars type = null;

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getOrderId() {
		return orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	public AssuranceTypeTars getType() {
		return type;
	}

	public void setType(AssuranceTypeTars type) {
		this.type = type;
	}

	public AssuranceTars() {
	}

	public AssuranceTars(String id, String orderId, AssuranceTypeTars type) {
		this.id = id;
		this.orderId = orderId;
		this.type = type;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(id);
		result = prime * result + TarsUtil.hashCode(orderId);
		result = prime * result + TarsUtil.hashCode(type);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof AssuranceTars)) {
			return false;
		}
		AssuranceTars other = (AssuranceTars) obj;
		return (
			TarsUtil.equals(id, other.id) &&
			TarsUtil.equals(orderId, other.orderId) &&
			TarsUtil.equals(type, other.type) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != id) {
			_os.write(id, 0);
		}
		if (null != orderId) {
			_os.write(orderId, 1);
		}
		if (null != type) {
			_os.write(type, 2);
		}
	}

	static AssuranceTypeTars cache_type;
	static { 
		cache_type = new AssuranceTypeTars();
	}

	public void readFrom(TarsInputStream _is) {
		this.id = _is.readString(0, false);
		this.orderId = _is.readString(1, false);
		this.type = (AssuranceTypeTars) _is.read(cache_type, 2, false);
	}

}
