// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package assurance.tars.assurance;

import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.annotation.*;
import com.qq.tars.common.support.Holder;

@Servant
public interface AssuranceControllerServant {

	public String home();

	public ResponsePlainAssurances getAllAssurances();

	public ResponseAssuranceTypeBeans getAllAssuranceType();

	public ResponseAssurance deleteAssurance(String assuranceId);

	public ResponseAssurance deleteAssuranceByOrderId(String orderId);

	public ResponseAssurance modifyAssurance(String assuranceId, String orderId, int typeIndex);

	public ResponseAssurance createNewAssurance(int typeIndex, String orderId);

	public ResponseAssurance getAssuranceById(String assuranceId);

	public ResponseAssurance findAssuranceByOrderId(String orderId);
}
