// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package assurance.tars.assurance;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class PlainAssuranceTars {

	@TarsStructProperty(order = 0, isRequire = false)
	public String id = "";
	@TarsStructProperty(order = 1, isRequire = false)
	public String orderId = "";
	@TarsStructProperty(order = 2, isRequire = false)
	public int typeIndex = 0;
	@TarsStructProperty(order = 3, isRequire = false)
	public String typeName = "";
	@TarsStructProperty(order = 4, isRequire = false)
	public double typePrice = 0;

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getOrderId() {
		return orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	public int getTypeIndex() {
		return typeIndex;
	}

	public void setTypeIndex(int typeIndex) {
		this.typeIndex = typeIndex;
	}

	public String getTypeName() {
		return typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	public double getTypePrice() {
		return typePrice;
	}

	public void setTypePrice(double typePrice) {
		this.typePrice = typePrice;
	}

	public PlainAssuranceTars() {
	}

	public PlainAssuranceTars(String id, String orderId, int typeIndex, String typeName, double typePrice) {
		this.id = id;
		this.orderId = orderId;
		this.typeIndex = typeIndex;
		this.typeName = typeName;
		this.typePrice = typePrice;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(id);
		result = prime * result + TarsUtil.hashCode(orderId);
		result = prime * result + TarsUtil.hashCode(typeIndex);
		result = prime * result + TarsUtil.hashCode(typeName);
		result = prime * result + TarsUtil.hashCode(typePrice);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof PlainAssuranceTars)) {
			return false;
		}
		PlainAssuranceTars other = (PlainAssuranceTars) obj;
		return (
			TarsUtil.equals(id, other.id) &&
			TarsUtil.equals(orderId, other.orderId) &&
			TarsUtil.equals(typeIndex, other.typeIndex) &&
			TarsUtil.equals(typeName, other.typeName) &&
			TarsUtil.equals(typePrice, other.typePrice) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != id) {
			_os.write(id, 0);
		}
		if (null != orderId) {
			_os.write(orderId, 1);
		}
		_os.write(typeIndex, 2);
		if (null != typeName) {
			_os.write(typeName, 3);
		}
		_os.write(typePrice, 4);
	}


	public void readFrom(TarsInputStream _is) {
		this.id = _is.readString(0, false);
		this.orderId = _is.readString(1, false);
		this.typeIndex = _is.read(typeIndex, 2, false);
		this.typeName = _is.readString(3, false);
		this.typePrice = _is.read(typePrice, 4, false);
	}

}
