// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package foodsearch.tars.food;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class AllTripFoodTars {

	@TarsStructProperty(order = 0, isRequire = false)
	public java.util.List<TrainFoodTars> trainFoodList = null;
	@TarsStructProperty(order = 1, isRequire = false)
	public java.util.Map<String, java.util.List<FoodStoreTars>> foodStoreListMap = null;

	public java.util.List<TrainFoodTars> getTrainFoodList() {
		return trainFoodList;
	}

	public void setTrainFoodList(java.util.List<TrainFoodTars> trainFoodList) {
		this.trainFoodList = trainFoodList;
	}

	public java.util.Map<String, java.util.List<FoodStoreTars>> getFoodStoreListMap() {
		return foodStoreListMap;
	}

	public void setFoodStoreListMap(java.util.Map<String, java.util.List<FoodStoreTars>> foodStoreListMap) {
		this.foodStoreListMap = foodStoreListMap;
	}

	public AllTripFoodTars() {
	}

	public AllTripFoodTars(java.util.List<TrainFoodTars> trainFoodList, java.util.Map<String, java.util.List<FoodStoreTars>> foodStoreListMap) {
		this.trainFoodList = trainFoodList;
		this.foodStoreListMap = foodStoreListMap;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(trainFoodList);
		result = prime * result + TarsUtil.hashCode(foodStoreListMap);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof AllTripFoodTars)) {
			return false;
		}
		AllTripFoodTars other = (AllTripFoodTars) obj;
		return (
			TarsUtil.equals(trainFoodList, other.trainFoodList) &&
			TarsUtil.equals(foodStoreListMap, other.foodStoreListMap) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != trainFoodList) {
			_os.write(trainFoodList, 0);
		}
		if (null != foodStoreListMap) {
			_os.write(foodStoreListMap, 1);
		}
	}

	static java.util.List<TrainFoodTars> cache_trainFoodList;
	static { 
		cache_trainFoodList = new java.util.ArrayList<TrainFoodTars>();
		TrainFoodTars var_3 = new TrainFoodTars();
		cache_trainFoodList.add(var_3);
	}
	static java.util.Map<String, java.util.List<FoodStoreTars>> cache_foodStoreListMap;
	static { 
		cache_foodStoreListMap = new java.util.HashMap<String, java.util.List<FoodStoreTars>>();
		String var_4 = "";
		java.util.List<FoodStoreTars> var_5 = new java.util.ArrayList<FoodStoreTars>();
		FoodStoreTars var_6 = new FoodStoreTars();
		var_5.add(var_6);
		cache_foodStoreListMap.put(var_4 ,var_5);
	}

	public void readFrom(TarsInputStream _is) {
		this.trainFoodList = (java.util.List<TrainFoodTars>) _is.read(cache_trainFoodList, 0, false);
		this.foodStoreListMap = (java.util.Map<String, java.util.List<FoodStoreTars>>) _is.read(cache_foodStoreListMap, 1, false);
	}

}
