// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package foodsearch.tars.food;

import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.annotation.*;
import com.qq.tars.common.support.Holder;

@Servant
public interface FoodControllerServant {

	public String home();

	public ResponseFoodOrderList findAllFoodOrder();

	public ResponseFoodOrder createFoodOrder(FoodOrderTars addFoodOrder);

	public ResponseFoodOrder updateFoodOrder(FoodOrderTars updateFoodOrder);

	public ResponseFoodOrder deleteFoodOrder(String orderId);

	public ResponseFoodOrder findFoodOrderByOrderId(String orderId);

	public ResponseAllTripFoodList getAllFood(String date, String startStation, String endStation, String tripId);
}
