// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package foodsearch.tars.food;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class FoodTars {

	@TarsStructProperty(order = 0, isRequire = false)
	public String foodName = "";
	@TarsStructProperty(order = 1, isRequire = false)
	public double price = 0;

	public String getFoodName() {
		return foodName;
	}

	public void setFoodName(String foodName) {
		this.foodName = foodName;
	}

	public double getPrice() {
		return price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public FoodTars() {
	}

	public FoodTars(String foodName, double price) {
		this.foodName = foodName;
		this.price = price;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(foodName);
		result = prime * result + TarsUtil.hashCode(price);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof FoodTars)) {
			return false;
		}
		FoodTars other = (FoodTars) obj;
		return (
			TarsUtil.equals(foodName, other.foodName) &&
			TarsUtil.equals(price, other.price) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != foodName) {
			_os.write(foodName, 0);
		}
		_os.write(price, 1);
	}


	public void readFrom(TarsInputStream _is) {
		this.foodName = _is.readString(0, false);
		this.price = _is.read(price, 1, false);
	}

}
