// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package foodsearch.tars.food;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class FoodOrderTars {

	@TarsStructProperty(order = 0, isRequire = false)
	public String id = "";
	@TarsStructProperty(order = 1, isRequire = false)
	public String orderId = "";
	@TarsStructProperty(order = 2, isRequire = false)
	public int foodType = 0;
	@TarsStructProperty(order = 3, isRequire = false)
	public String stationName = "";
	@TarsStructProperty(order = 4, isRequire = false)
	public String storeName = "";
	@TarsStructProperty(order = 5, isRequire = false)
	public String foodName = "";
	@TarsStructProperty(order = 6, isRequire = false)
	public double price = 0;

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getOrderId() {
		return orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	public int getFoodType() {
		return foodType;
	}

	public void setFoodType(int foodType) {
		this.foodType = foodType;
	}

	public String getStationName() {
		return stationName;
	}

	public void setStationName(String stationName) {
		this.stationName = stationName;
	}

	public String getStoreName() {
		return storeName;
	}

	public void setStoreName(String storeName) {
		this.storeName = storeName;
	}

	public String getFoodName() {
		return foodName;
	}

	public void setFoodName(String foodName) {
		this.foodName = foodName;
	}

	public double getPrice() {
		return price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public FoodOrderTars() {
	}

	public FoodOrderTars(String id, String orderId, int foodType, String stationName, String storeName, String foodName, double price) {
		this.id = id;
		this.orderId = orderId;
		this.foodType = foodType;
		this.stationName = stationName;
		this.storeName = storeName;
		this.foodName = foodName;
		this.price = price;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(id);
		result = prime * result + TarsUtil.hashCode(orderId);
		result = prime * result + TarsUtil.hashCode(foodType);
		result = prime * result + TarsUtil.hashCode(stationName);
		result = prime * result + TarsUtil.hashCode(storeName);
		result = prime * result + TarsUtil.hashCode(foodName);
		result = prime * result + TarsUtil.hashCode(price);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof FoodOrderTars)) {
			return false;
		}
		FoodOrderTars other = (FoodOrderTars) obj;
		return (
			TarsUtil.equals(id, other.id) &&
			TarsUtil.equals(orderId, other.orderId) &&
			TarsUtil.equals(foodType, other.foodType) &&
			TarsUtil.equals(stationName, other.stationName) &&
			TarsUtil.equals(storeName, other.storeName) &&
			TarsUtil.equals(foodName, other.foodName) &&
			TarsUtil.equals(price, other.price) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != id) {
			_os.write(id, 0);
		}
		if (null != orderId) {
			_os.write(orderId, 1);
		}
		_os.write(foodType, 2);
		if (null != stationName) {
			_os.write(stationName, 3);
		}
		if (null != storeName) {
			_os.write(storeName, 4);
		}
		if (null != foodName) {
			_os.write(foodName, 5);
		}
		_os.write(price, 6);
	}


	public void readFrom(TarsInputStream _is) {
		this.id = _is.readString(0, false);
		this.orderId = _is.readString(1, false);
		this.foodType = _is.read(foodType, 2, false);
		this.stationName = _is.readString(3, false);
		this.storeName = _is.readString(4, false);
		this.foodName = _is.readString(5, false);
		this.price = _is.read(price, 6, false);
	}

}
