// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package route.tars.route;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class RouteTars {

	@TarsStructProperty(order = 0, isRequire = false)
	public String id = "";
	@TarsStructProperty(order = 1, isRequire = false)
	public java.util.List<String> stations = null;
	@TarsStructProperty(order = 2, isRequire = false)
	public java.util.List<java.lang.Integer> distances = null;
	@TarsStructProperty(order = 3, isRequire = false)
	public String startStationId = "";
	@TarsStructProperty(order = 4, isRequire = false)
	public String terminalStationId = "";

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public java.util.List<String> getStations() {
		return stations;
	}

	public void setStations(java.util.List<String> stations) {
		this.stations = stations;
	}

	public java.util.List<java.lang.Integer> getDistances() {
		return distances;
	}

	public void setDistances(java.util.List<java.lang.Integer> distances) {
		this.distances = distances;
	}

	public String getStartStationId() {
		return startStationId;
	}

	public void setStartStationId(String startStationId) {
		this.startStationId = startStationId;
	}

	public String getTerminalStationId() {
		return terminalStationId;
	}

	public void setTerminalStationId(String terminalStationId) {
		this.terminalStationId = terminalStationId;
	}

	public RouteTars() {
	}

	public RouteTars(String id, java.util.List<String> stations, java.util.List<java.lang.Integer> distances, String startStationId, String terminalStationId) {
		this.id = id;
		this.stations = stations;
		this.distances = distances;
		this.startStationId = startStationId;
		this.terminalStationId = terminalStationId;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(id);
		result = prime * result + TarsUtil.hashCode(stations);
		result = prime * result + TarsUtil.hashCode(distances);
		result = prime * result + TarsUtil.hashCode(startStationId);
		result = prime * result + TarsUtil.hashCode(terminalStationId);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof RouteTars)) {
			return false;
		}
		RouteTars other = (RouteTars) obj;
		return (
			TarsUtil.equals(id, other.id) &&
			TarsUtil.equals(stations, other.stations) &&
			TarsUtil.equals(distances, other.distances) &&
			TarsUtil.equals(startStationId, other.startStationId) &&
			TarsUtil.equals(terminalStationId, other.terminalStationId) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != id) {
			_os.write(id, 0);
		}
		if (null != stations) {
			_os.write(stations, 1);
		}
		if (null != distances) {
			_os.write(distances, 2);
		}
		if (null != startStationId) {
			_os.write(startStationId, 3);
		}
		if (null != terminalStationId) {
			_os.write(terminalStationId, 3);
		}
	}

	static java.util.List<String> cache_stations;
	static { 
		cache_stations = new java.util.ArrayList<String>();
		String var_1 = "";
		cache_stations.add(var_1);
	}
	static java.util.List<java.lang.Integer> cache_distances;
	static { 
		cache_distances = new java.util.ArrayList<java.lang.Integer>();
		int var_2 = 0;
		cache_distances.add(var_2);
	}

	public void readFrom(TarsInputStream _is) {
		this.id = _is.readString(0, false);
		this.stations = (java.util.List<String>) _is.read(cache_stations, 1, false);
		this.distances = (java.util.List<java.lang.Integer>) _is.read(cache_distances, 2, false);
		this.startStationId = _is.readString(3, false);
		this.terminalStationId = _is.readString(3, false);
	}

}
