// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package consign.tars.consign;

import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.annotation.*;
import com.qq.tars.common.support.Holder;

@Servant
public interface ConsignControllerServant {

	public String home();

	public ResponseConsign insertConsign(ConsignTars request);

	public ResponseConsign updateConsign(ConsignTars request);

	public ResponseConsignList findByAccountId(String id);

	public ResponseConsign findByOrderId(String id);

	public ResponseConsignList findByConsignee(String consignee);
}
