// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package consign.tars.consign;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class ConsignTars {

	@TarsStructProperty(order = 0, isRequire = false)
	public String id = "";
	@TarsStructProperty(order = 1, isRequire = false)
	public String orderId = "";
	@TarsStructProperty(order = 2, isRequire = false)
	public String accountId = "";
	@TarsStructProperty(order = 3, isRequire = false)
	public String handleDate = "";
	@TarsStructProperty(order = 4, isRequire = false)
	public String targetDate = "";
	@TarsStructProperty(order = 5, isRequire = false)
	public String from = "";
	@TarsStructProperty(order = 6, isRequire = false)
	public String to = "";
	@TarsStructProperty(order = 7, isRequire = false)
	public String consignee = "";
	@TarsStructProperty(order = 8, isRequire = false)
	public String phone = "";
	@TarsStructProperty(order = 9, isRequire = false)
	public double weight = 0;
	@TarsStructProperty(order = 10, isRequire = false)
	public boolean isWithin = false;
	@TarsStructProperty(order = 11, isRequire = false)
	public double price = 0;

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getOrderId() {
		return orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	public String getAccountId() {
		return accountId;
	}

	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}

	public String getHandleDate() {
		return handleDate;
	}

	public void setHandleDate(String handleDate) {
		this.handleDate = handleDate;
	}

	public String getTargetDate() {
		return targetDate;
	}

	public void setTargetDate(String targetDate) {
		this.targetDate = targetDate;
	}

	public String getFrom() {
		return from;
	}

	public void setFrom(String from) {
		this.from = from;
	}

	public String getTo() {
		return to;
	}

	public void setTo(String to) {
		this.to = to;
	}

	public String getConsignee() {
		return consignee;
	}

	public void setConsignee(String consignee) {
		this.consignee = consignee;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public double getWeight() {
		return weight;
	}

	public void setWeight(double weight) {
		this.weight = weight;
	}

	public boolean isWithin() {
		return isWithin;
	}

	public void setWithin(boolean isWithin) {
		this.isWithin = isWithin;
	}

	public double getPrice() {
		return price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public ConsignTars() {
	}

	public ConsignTars(String id, String orderId, String accountId, String handleDate, String targetDate, String from, String to, String consignee, String phone, double weight, boolean isWithin, double price) {
		this.id = id;
		this.orderId = orderId;
		this.accountId = accountId;
		this.handleDate = handleDate;
		this.targetDate = targetDate;
		this.from = from;
		this.to = to;
		this.consignee = consignee;
		this.phone = phone;
		this.weight = weight;
		this.isWithin = isWithin;
		this.price = price;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(id);
		result = prime * result + TarsUtil.hashCode(orderId);
		result = prime * result + TarsUtil.hashCode(accountId);
		result = prime * result + TarsUtil.hashCode(handleDate);
		result = prime * result + TarsUtil.hashCode(targetDate);
		result = prime * result + TarsUtil.hashCode(from);
		result = prime * result + TarsUtil.hashCode(to);
		result = prime * result + TarsUtil.hashCode(consignee);
		result = prime * result + TarsUtil.hashCode(phone);
		result = prime * result + TarsUtil.hashCode(weight);
		result = prime * result + TarsUtil.hashCode(isWithin);
		result = prime * result + TarsUtil.hashCode(price);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof ConsignTars)) {
			return false;
		}
		ConsignTars other = (ConsignTars) obj;
		return (
			TarsUtil.equals(id, other.id) &&
			TarsUtil.equals(orderId, other.orderId) &&
			TarsUtil.equals(accountId, other.accountId) &&
			TarsUtil.equals(handleDate, other.handleDate) &&
			TarsUtil.equals(targetDate, other.targetDate) &&
			TarsUtil.equals(from, other.from) &&
			TarsUtil.equals(to, other.to) &&
			TarsUtil.equals(consignee, other.consignee) &&
			TarsUtil.equals(phone, other.phone) &&
			TarsUtil.equals(weight, other.weight) &&
			TarsUtil.equals(isWithin, other.isWithin) &&
			TarsUtil.equals(price, other.price) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != id) {
			_os.write(id, 0);
		}
		if (null != orderId) {
			_os.write(orderId, 1);
		}
		if (null != accountId) {
			_os.write(accountId, 2);
		}
		if (null != handleDate) {
			_os.write(handleDate, 3);
		}
		if (null != targetDate) {
			_os.write(targetDate, 4);
		}
		if (null != from) {
			_os.write(from, 5);
		}
		if (null != to) {
			_os.write(to, 6);
		}
		if (null != consignee) {
			_os.write(consignee, 7);
		}
		if (null != phone) {
			_os.write(phone, 8);
		}
		_os.write(weight, 9);
		_os.write(isWithin, 10);
		_os.write(price, 11);
	}


	public void readFrom(TarsInputStream _is) {
		this.id = _is.readString(0, false);
		this.orderId = _is.readString(1, false);
		this.accountId = _is.readString(2, false);
		this.handleDate = _is.readString(3, false);
		this.targetDate = _is.readString(4, false);
		this.from = _is.readString(5, false);
		this.to = _is.readString(6, false);
		this.consignee = _is.readString(7, false);
		this.phone = _is.readString(8, false);
		this.weight = _is.read(weight, 9, false);
		this.isWithin = _is.read(isWithin, 10, false);
		this.price = _is.read(price, 11, false);
	}

}
