// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package food.tars.foodmap;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class FoodStoreTars {

	@TarsStructProperty(order = 0, isRequire = false)
	public String id = "";
	@TarsStructProperty(order = 1, isRequire = false)
	public String stationId = "";
	@TarsStructProperty(order = 2, isRequire = false)
	public String storeName = "";
	@TarsStructProperty(order = 3, isRequire = false)
	public String telephone = "";
	@TarsStructProperty(order = 4, isRequire = false)
	public String businessTime = "";
	@TarsStructProperty(order = 5, isRequire = false)
	public double deliveryFee = 0;
	@TarsStructProperty(order = 6, isRequire = false)
	public java.util.List<FoodTars> foodList = null;

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getStationId() {
		return stationId;
	}

	public void setStationId(String stationId) {
		this.stationId = stationId;
	}

	public String getStoreName() {
		return storeName;
	}

	public void setStoreName(String storeName) {
		this.storeName = storeName;
	}

	public String getTelephone() {
		return telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public String getBusinessTime() {
		return businessTime;
	}

	public void setBusinessTime(String businessTime) {
		this.businessTime = businessTime;
	}

	public double getDeliveryFee() {
		return deliveryFee;
	}

	public void setDeliveryFee(double deliveryFee) {
		this.deliveryFee = deliveryFee;
	}

	public java.util.List<FoodTars> getFoodList() {
		return foodList;
	}

	public void setFoodList(java.util.List<FoodTars> foodList) {
		this.foodList = foodList;
	}

	public FoodStoreTars() {
	}

	public FoodStoreTars(String id, String stationId, String storeName, String telephone, String businessTime, double deliveryFee, java.util.List<FoodTars> foodList) {
		this.id = id;
		this.stationId = stationId;
		this.storeName = storeName;
		this.telephone = telephone;
		this.businessTime = businessTime;
		this.deliveryFee = deliveryFee;
		this.foodList = foodList;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(id);
		result = prime * result + TarsUtil.hashCode(stationId);
		result = prime * result + TarsUtil.hashCode(storeName);
		result = prime * result + TarsUtil.hashCode(telephone);
		result = prime * result + TarsUtil.hashCode(businessTime);
		result = prime * result + TarsUtil.hashCode(deliveryFee);
		result = prime * result + TarsUtil.hashCode(foodList);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof FoodStoreTars)) {
			return false;
		}
		FoodStoreTars other = (FoodStoreTars) obj;
		return (
			TarsUtil.equals(id, other.id) &&
			TarsUtil.equals(stationId, other.stationId) &&
			TarsUtil.equals(storeName, other.storeName) &&
			TarsUtil.equals(telephone, other.telephone) &&
			TarsUtil.equals(businessTime, other.businessTime) &&
			TarsUtil.equals(deliveryFee, other.deliveryFee) &&
			TarsUtil.equals(foodList, other.foodList) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != id) {
			_os.write(id, 0);
		}
		if (null != stationId) {
			_os.write(stationId, 1);
		}
		if (null != storeName) {
			_os.write(storeName, 2);
		}
		if (null != telephone) {
			_os.write(telephone, 3);
		}
		if (null != businessTime) {
			_os.write(businessTime, 4);
		}
		_os.write(deliveryFee, 5);
		if (null != foodList) {
			_os.write(foodList, 6);
		}
	}

	static java.util.List<FoodTars> cache_foodList;
	static { 
		cache_foodList = new java.util.ArrayList<FoodTars>();
		FoodTars var_1 = new FoodTars();
		cache_foodList.add(var_1);
	}

	public void readFrom(TarsInputStream _is) {
		this.id = _is.readString(0, false);
		this.stationId = _is.readString(1, false);
		this.storeName = _is.readString(2, false);
		this.telephone = _is.readString(3, false);
		this.businessTime = _is.readString(4, false);
		this.deliveryFee = _is.read(deliveryFee, 5, false);
		this.foodList = (java.util.List<FoodTars>) _is.read(cache_foodList, 6, false);
	}

}
