// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package food.tars.foodmap;

import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.annotation.*;
import com.qq.tars.common.support.Holder;

@Servant
public interface TrainFoodControllerServant {

	public String home();

	public ResponseTrainFoods getAllTrainFood();

	public ResponseTrainFoods getTrainFoodOfTrip(String tripId);
}
