// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package fdse.microservice.tars.basic;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TripTars {

	@TarsStructProperty(order = 0, isRequire = false)
	public TripIdTars tripId = null;
	@TarsStructProperty(order = 1, isRequire = false)
	public String trainTypeId = "";
	@TarsStructProperty(order = 2, isRequire = false)
	public String routeId = "";
	@TarsStructProperty(order = 3, isRequire = false)
	public String startingStationId = "";
	@TarsStructProperty(order = 4, isRequire = false)
	public String stationsId = "";
	@TarsStructProperty(order = 5, isRequire = false)
	public String terminalStationId = "";
	@TarsStructProperty(order = 6, isRequire = false)
	public long startingTime = 0;
	@TarsStructProperty(order = 7, isRequire = false)
	public long endTime = 0;

	public TripIdTars getTripId() {
		return tripId;
	}

	public void setTripId(TripIdTars tripId) {
		this.tripId = tripId;
	}

	public String getTrainTypeId() {
		return trainTypeId;
	}

	public void setTrainTypeId(String trainTypeId) {
		this.trainTypeId = trainTypeId;
	}

	public String getRouteId() {
		return routeId;
	}

	public void setRouteId(String routeId) {
		this.routeId = routeId;
	}

	public String getStartingStationId() {
		return startingStationId;
	}

	public void setStartingStationId(String startingStationId) {
		this.startingStationId = startingStationId;
	}

	public String getStationsId() {
		return stationsId;
	}

	public void setStationsId(String stationsId) {
		this.stationsId = stationsId;
	}

	public String getTerminalStationId() {
		return terminalStationId;
	}

	public void setTerminalStationId(String terminalStationId) {
		this.terminalStationId = terminalStationId;
	}

	public long getStartingTime() {
		return startingTime;
	}

	public void setStartingTime(long startingTime) {
		this.startingTime = startingTime;
	}

	public long getEndTime() {
		return endTime;
	}

	public void setEndTime(long endTime) {
		this.endTime = endTime;
	}

	public TripTars() {
	}

	public TripTars(TripIdTars tripId, String trainTypeId, String routeId, String startingStationId, String stationsId, String terminalStationId, long startingTime, long endTime) {
		this.tripId = tripId;
		this.trainTypeId = trainTypeId;
		this.routeId = routeId;
		this.startingStationId = startingStationId;
		this.stationsId = stationsId;
		this.terminalStationId = terminalStationId;
		this.startingTime = startingTime;
		this.endTime = endTime;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(tripId);
		result = prime * result + TarsUtil.hashCode(trainTypeId);
		result = prime * result + TarsUtil.hashCode(routeId);
		result = prime * result + TarsUtil.hashCode(startingStationId);
		result = prime * result + TarsUtil.hashCode(stationsId);
		result = prime * result + TarsUtil.hashCode(terminalStationId);
		result = prime * result + TarsUtil.hashCode(startingTime);
		result = prime * result + TarsUtil.hashCode(endTime);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TripTars)) {
			return false;
		}
		TripTars other = (TripTars) obj;
		return (
			TarsUtil.equals(tripId, other.tripId) &&
			TarsUtil.equals(trainTypeId, other.trainTypeId) &&
			TarsUtil.equals(routeId, other.routeId) &&
			TarsUtil.equals(startingStationId, other.startingStationId) &&
			TarsUtil.equals(stationsId, other.stationsId) &&
			TarsUtil.equals(terminalStationId, other.terminalStationId) &&
			TarsUtil.equals(startingTime, other.startingTime) &&
			TarsUtil.equals(endTime, other.endTime) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != tripId) {
			_os.write(tripId, 0);
		}
		if (null != trainTypeId) {
			_os.write(trainTypeId, 1);
		}
		if (null != routeId) {
			_os.write(routeId, 2);
		}
		if (null != startingStationId) {
			_os.write(startingStationId, 3);
		}
		if (null != stationsId) {
			_os.write(stationsId, 4);
		}
		if (null != terminalStationId) {
			_os.write(terminalStationId, 5);
		}
		_os.write(startingTime, 6);
		_os.write(endTime, 7);
	}

	static TripIdTars cache_tripId;
	static { 
		cache_tripId = new TripIdTars();
	}

	public void readFrom(TarsInputStream _is) {
		this.tripId = (TripIdTars) _is.read(cache_tripId, 0, false);
		this.trainTypeId = _is.readString(1, false);
		this.routeId = _is.readString(2, false);
		this.startingStationId = _is.readString(3, false);
		this.stationsId = _is.readString(4, false);
		this.terminalStationId = _is.readString(5, false);
		this.startingTime = _is.read(startingTime, 6, false);
		this.endTime = _is.read(endTime, 7, false);
	}

}
