// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package fdse.microservice.tars.basic;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class TypeTars {

	@TarsStructProperty(order = 0, isRequire = false)
	public String name = "";
	@TarsStructProperty(order = 1, isRequire = false)
	public int index = 0;

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getIndex() {
		return index;
	}

	public void setIndex(int index) {
		this.index = index;
	}

	public TypeTars() {
	}

	public TypeTars(String name, int index) {
		this.name = name;
		this.index = index;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(name);
		result = prime * result + TarsUtil.hashCode(index);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof TypeTars)) {
			return false;
		}
		TypeTars other = (TypeTars) obj;
		return (
			TarsUtil.equals(name, other.name) &&
			TarsUtil.equals(index, other.index) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != name) {
			_os.write(name, 0);
		}
		_os.write(index, 1);
	}


	public void readFrom(TarsInputStream _is) {
		this.name = _is.readString(0, false);
		this.index = _is.read(index, 1, false);
	}

}
