// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package adminbasic.tars.rpc.priceconfig;

import com.qq.tars.rpc.protocol.tars.support.TarsAbstractCallback;

public abstract class PriceControllerPrxCallback extends TarsAbstractCallback {

	public abstract void callback_home(String ret);

	public abstract void callback_query(ResponsePriceConfig ret);

	public abstract void callback_queryAll(ResponsePriceConfigs ret);

	public abstract void callback_create(ResponsePriceConfig ret);

	public abstract void callback_delete(ResponsePriceConfig ret);

	public abstract void callback_update(ResponsePriceConfig ret);

}
