// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package price.tars.priceconfig;

import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.annotation.*;
import com.qq.tars.common.support.Holder;

@Servant
public interface PriceControllerServant {

	public String home();

	public ResponsePriceConfig query(String routeId, String trainType);

	public ResponsePriceConfigs queryAll();

	public ResponsePriceConfig create(PriceConfigTars info);

	public ResponsePriceConfig delete(PriceConfigTars info);

	public ResponsePriceConfig update(PriceConfigTars info);
}
