// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package adminorder.tars.adminorder;

import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.annotation.*;
import com.qq.tars.common.support.Holder;

@Servant
public interface AdminOrderControllerServant {

	public String home();

	public Response getAllOrders(@TarsHolder Holder<java.util.List<OrderTars>> outData);

	public Response addOrder(OrderTars request, @TarsHolder Holder<OrderTars> outData);

	public Response updateOrder(OrderTars request, @TarsHolder Holder<OrderTars> outData);

	public Response deleteOrder(String orderId, String trainNumber, @TarsHolder Holder<OrderTars> outData);
}
