// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package other.tars.orderother;

import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.annotation.*;
import com.qq.tars.common.support.Holder;

@Servant
public interface OrderOtherControllerServant {

	public String home();

	public ResponseLeftTicketInfo getTicketListByDateAndTripId(SeatTars seatRequest);

	public ResponseOrder createNewOrder(OrderTars createOrder);

	public ResponseOrder addcreateNewOrder(OrderTars order);

	public ResponseOrderList queryOrders(QueryInfoTars qi);

	public ResponseOrderList queryOrdersForRefresh(QueryInfoTars qi);

	public ResponseSoldTicket calculateSoldTicket(int travelDate, String trainNumber);

	public ResponseString getOrderPrice(String orderId);

	public ResponseOrder payOrder(String orderId);

	public ResponseOrder getOrderById(String orderId);

	public ResponseOrder modifyOrder(String orderId, int status);

	public ResponseOrderSecurity securityInfoCheck(long checkDate, String accountId);

	public ResponseOrder saveOrderInfo(OrderTars orderInfo);

	public ResponseOrder updateOrder(OrderTars order);

	public ResponseString deleteOrder(String orderId);

	public ResponseOrderList findAllOrder();
}
