// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package inside_payment.tars.insidepayment;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class AccountInfoTars {

	@TarsStructProperty(order = 0, isRequire = false)
	public String userId = "";
	@TarsStructProperty(order = 1, isRequire = false)
	public String money = "";

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getMoney() {
		return money;
	}

	public void setMoney(String money) {
		this.money = money;
	}

	public AccountInfoTars() {
	}

	public AccountInfoTars(String userId, String money) {
		this.userId = userId;
		this.money = money;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(userId);
		result = prime * result + TarsUtil.hashCode(money);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof AccountInfoTars)) {
			return false;
		}
		AccountInfoTars other = (AccountInfoTars) obj;
		return (
			TarsUtil.equals(userId, other.userId) &&
			TarsUtil.equals(money, other.money) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != userId) {
			_os.write(userId, 0);
		}
		if (null != money) {
			_os.write(money, 1);
		}
	}


	public void readFrom(TarsInputStream _is) {
		this.userId = _is.readString(0, false);
		this.money = _is.readString(1, false);
	}

}
