// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package inside_payment.tars.insidepayment;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class BalanceTars {

	@TarsStructProperty(order = 0, isRequire = false)
	public String userId = "";
	@TarsStructProperty(order = 1, isRequire = false)
	public String balance = "";

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getBalance() {
		return balance;
	}

	public void setBalance(String balance) {
		this.balance = balance;
	}

	public BalanceTars() {
	}

	public BalanceTars(String userId, String balance) {
		this.userId = userId;
		this.balance = balance;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(userId);
		result = prime * result + TarsUtil.hashCode(balance);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof BalanceTars)) {
			return false;
		}
		BalanceTars other = (BalanceTars) obj;
		return (
			TarsUtil.equals(userId, other.userId) &&
			TarsUtil.equals(balance, other.balance) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != userId) {
			_os.write(userId, 0);
		}
		if (null != balance) {
			_os.write(balance, 1);
		}
	}


	public void readFrom(TarsInputStream _is) {
		this.userId = _is.readString(0, false);
		this.balance = _is.readString(1, false);
	}

}
