// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package inside_payment.tars.insidepayment;

import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.annotation.*;
import com.qq.tars.common.support.Holder;

@Servant
public interface InsidePaymentControllerServant {

	public String home();

	public ResponsePaymentInfo pay(PaymentInfoTars info);

	public ResponseAccountInfo createAccount(AccountInfoTars info);

	public ResponsePaymentInfo addMoney(String userId, String money);

	public ResponsePaymentInfoList queryPayment();

	public ResponseBalanceList queryAccount();

	public ResponsePaymentInfo drawBack(String userId, String money);

	public ResponsePaymentInfo payDifference(PaymentInfoTars info);

	public ResponsePaymentInfo queryAddMoney();
}
