// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package inside_payment.tars.insidepayment;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class PaymentInfoTars {

	@TarsStructProperty(order = 0, isRequire = false)
	public String userId = "";
	@TarsStructProperty(order = 1, isRequire = false)
	public String orderId = "";
	@TarsStructProperty(order = 2, isRequire = false)
	public String tripId = "";
	@TarsStructProperty(order = 3, isRequire = false)
	public String price = "";

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getOrderId() {
		return orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	public String getTripId() {
		return tripId;
	}

	public void setTripId(String tripId) {
		this.tripId = tripId;
	}

	public String getPrice() {
		return price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	public PaymentInfoTars() {
	}

	public PaymentInfoTars(String userId, String orderId, String tripId, String price) {
		this.userId = userId;
		this.orderId = orderId;
		this.tripId = tripId;
		this.price = price;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(userId);
		result = prime * result + TarsUtil.hashCode(orderId);
		result = prime * result + TarsUtil.hashCode(tripId);
		result = prime * result + TarsUtil.hashCode(price);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof PaymentInfoTars)) {
			return false;
		}
		PaymentInfoTars other = (PaymentInfoTars) obj;
		return (
			TarsUtil.equals(userId, other.userId) &&
			TarsUtil.equals(orderId, other.orderId) &&
			TarsUtil.equals(tripId, other.tripId) &&
			TarsUtil.equals(price, other.price) 
		);
	}

	public void writeTo(TarsOutputStream _os) {
		if (null != userId) {
			_os.write(userId, 0);
		}
		if (null != orderId) {
			_os.write(orderId, 1);
		}
		if (null != tripId) {
			_os.write(tripId, 2);
		}
		if (null != price) {
			_os.write(price, 3);
		}
	}


	public void readFrom(TarsInputStream _is) {
		this.userId = _is.readString(0, false);
		this.orderId = _is.readString(1, false);
		this.tripId = _is.readString(2, false);
		this.price = _is.readString(3, false);
	}

}
