// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package fdse.microservice.tars.station;

import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.annotation.*;
import com.qq.tars.common.support.Holder;

@Servant
public interface StationControllerServant {

	public String home();

	public ResponseStations query();

	public ResponseStation create(StationTars station);

	public ResponseStation update(StationTars station);

	public ResponseStation delete(StationTars station);

	public ResponseString queryForStationId(String stationName);

	public ResponseStringList queryForIdBatch(java.util.List<String> stationNameList);

	public ResponseString queryById(String stationId);

	public ResponseStringList queryForNameBatch(java.util.List<String> stationIdList);
}
