// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package execute.tars.execute;

import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.annotation.*;
import com.qq.tars.common.support.Holder;

@Servant
public interface ExecuteControlllerServant {

	public String home();

	public Response executeTicket(String orderId);

	public Response collectTicket(String orderId);
}
