// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.0.1.
// **********************************************************************

package train.tars.train;

import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.annotation.*;
import com.qq.tars.common.support.Holder;

@Servant
public interface TrainControllerServant {

	public String home();

	public ResponseTrainType create(TrainTypeTars trainType);

	public ResponseTrainType retrieve(String id);

	public ResponseTrainType update(TrainTypeTars trainType);

	public ResponseTrainType delete(String id);

	public ResponseTrainTypes query();
}
